
version: 2
jobs:
    "java":
        docker:
          - image: circleci/openjdk:8-jdk
          
        working_directory: ~/repo

        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb

        steps:
          - checkout

          - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "java/FMU-proxy/build.gradle" }}
              - v1-dependencies-

          - run: 'cd java/FMU-proxy && gradle dependencies'

          - save_cache:
              paths:
                - ~/.gradle
              key: v1-dependencies-{{ checksum "java/FMU-proxy/build.gradle" }}

          - run: 'cd java/FMU-proxy && gradle test'
          - run: 'cd java/FMU-proxy && gradle shadowJar'

          - store_artifacts:
              path: 'java/FMU-proxy/fmu-proxy/build/libs/fmu-proxy.jar'
              destination: 'fmu-proxy.jar'

    "cpp_conan":
      docker:
        - image: lasote/conangcc7
      steps:
        - checkout

        - run:
            name: Initialize git sub-modules
            command: 'git submodule update --init --recursive && git submodule update --remote'
        - run:
            name: Update conan
            command: 'sudo pip3 install conan --upgrade'

        - restore_cache:
            keys:
              - v2-conan-cache-{{ checksum "cpp/FMU-proxy/conanfile.py" }}

        - run:
            name: Add conan remote 'inexorgame'
            command: 'conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan" --f'
        - run:
            name: Add conan remotes 'bincrafters'
            command: 'conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan" --f'

        - run:
            name: Conan install
            command: 'cd cpp/FMU-proxy && conan install . -s build_type=Release -s compiler.libcxx=libstdc++11 --install-folder=build --build=missing'

        - save_cache:
            paths:
              - ~/.conan
            key: v2-conan-cache-{{ checksum "cpp/FMU-proxy/conanfile.py" }}

        - run:
            name: Creating Build Files
            command: 'cd cpp/FMU-proxy && cmake -H. -Bbuild -DFMU_PROXY_BUILD_TOOL=ON -DFMU_PROXY_BUILD_TESTS=ON -DFMU_PROXY_BUILD_EXAMPLES=ON'
        - run:
            name: Creating Binary Files
            command: 'cd cpp/FMU-proxy && cmake --build build'

        - store_artifacts:
            path: 'cpp/FMU-proxy/build/bin/fmu_proxy'
            destination: 'fmu_proxy_cpp'

workflows:
    version: 2
    build:
        jobs: 
            - "java"
            - "cpp_conan"
